Repository monsieurbiz/SyliusNoCommercePlugin, pull requests merged in 2021-09, with the labels that each got.

#14 Fix PHPCS errors
  src/DependencyInjection/RemoveSyliusDataCollectorsPass.php
  src/Model/ConfigInterface.php
Labels: Status: needs review, quick win

#16 Remove scrutinizer's badge in README
  README.md
Labels: Priority: low, Status: needs review, quick win

#13 Feature: Add the possibility to disable firewalls
  composer.json
  src/DependencyInjection/FirewallRegistryPass.php
  src/EventListener/DisableFirewallListener.php
  src/Firewall/Registry.php
  src/Firewall/RegistryInterface.php
  src/Form/Type/Settings/NoCommerceType.php
  src/MonsieurBizSyliusNoCommercePlugin.php
  src/Resources/config/config.yaml
  src/Resources/config/monsieurbiz/settings.yaml
  src/Resources/config/services.yaml
  src/Resources/translations/messages.en.yaml
  src/Resources/translations/messages.fr.yaml
Labels: Status: needs review, enhancement

#18 Update test application to Sylius 1.10 and fix default configuration
  composer.json
  recipes/1.0-dev
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MonsieurBizSyliusNoCommerceExtension.php
  symfony.lock
  tests/Application/.env
  tests/Application/.env.test
  tests/Application/.eslintrc.js
  tests/Application/config/bundles.php
  tests/Application/config/jwt
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/dev/jms_serializer.yaml
  tests/Application/config/packages/fos_rest.yaml
  tests/Application/config/packages/jms_serializer.yaml
  tests/Application/config/packages/lexik_jwt_authentication.yaml
  tests/Application/config/packages/liip_imagine.yaml
  tests/Application/config/packages/monsieurbiz_settings_plugin.yaml
  tests/Application/config/packages/routing.yaml
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/stof_doctrine_extensions.yaml
  tests/Application/config/packages/swiftmailer.yaml
  tests/Application/config/packages/translation.yaml
  tests/Application/config/packages/twig.yaml
  tests/Application/config/packages/validator.yaml
  tests/Application/config/routes.yaml
  tests/Application/config/routes/monsieurbiz_settings_plugin.yaml
  tests/Application/config/routes/sylius_admin.yaml
  tests/Application/config/routes/sylius_admin_api.yaml
  tests/Application/config/routes/sylius_api.yaml
  tests/Application/config/routes/sylius_shop.yaml
  tests/Application/config/secrets
Labels: Priority: high, Status: needs review, enhancement

#21 Improve recipe 1.0
  recipes/1.0/manifest.json
  recipes/1.0/post-install.txt
Labels: Status: needs review, quick win
