Repository monsieurbiz/SyliusNoCommercePlugin, pull requests merged in 2021-03, with the labels that each got.

#8 Make getExtendedTypes static to be compatible to Symfony 5
  src/Form/Extension/ChannelTypeExtension.php
Labels: Status: needs review, quick win

#9 Add config to enable customers (users)
  Makefile
  README.md
  recipes/1.0/config/packages/monsieurbiz_sylius_nocommerce_plugin.yaml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MonsieurBizSyliusNoCommerceExtension.php
  src/Kernel/SyliusNoCommerceKernelTrait.php
  src/Menu/AdminMenuListener.php
  src/Model/Config.php
  src/Model/ConfigInterface.php
  src/Resources/config/services.yaml
  src/Routing/RouteCollectionBuilder.php
  symfony.lock
  tests/Application/config/bootstrap.php
Labels: Status: needs review

#10 Do not collect the cart in the profiler
  src/DependencyInjection/RemoveSyliusDataCollectorsPass.php
  src/MonsieurBizSyliusNoCommercePlugin.php
Labels: Priority: critical, Status: needs review, enhancement
